server.port=8080
spring.application.name=energy-analysis

# FastAPI backend URL
fastapi.base-url=http://localhost:8000

# CORS configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

# Konfiguracja Bazy Danych
app.db.url=${DB_URL}
app.db.user=${DB_USER}
app.db.password=${DB_PASSWORD}